config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    registrations: 'registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :posts
  resources :comments
  resources :likes
  resources :users
  resources :invitations, :only => [:index, :new, :create, :destroy]
  resources :friends, :only => [:index, :new, :create, :destroy]
  resources :conversations
  resources :messages
  
  devise_scope :user do
    root to: "devise/sessions#new"
  end
  get 'profiles', to: 'users#show'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/user.rb
class User < ApplicationRecord
  require 'pry'
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  devise :omniauthable, :omniauth_providers => [:facebook]
  has_many :posts, dependent: :destroy

  has_many :invitations, foreign_key: :invited_user_id
  has_many :friend_requests, through: :invitations

  has_many :friends, foreign_key: :user_id


  mount_uploader :avatar, AvatarUploader

  mount_uploader :cover, AvatarUploader

  has_many :likes

  has_many :messages
  has_many :conversations, foreign_key: :sender_id
  
  def self.search(name)
    user = User.where('name = ?', name) if name
  end

  def self.searchfriends(id)
    friends = Friend.where('user_id = ? or friend_id = ?', id, id)
  end


  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name   # assuming the user model has a name
      user.uploaded_url = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails, 
      # uncomment the line below to skip the confirmation emails.
      #user.skip_confirmation!
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # See https://github.com/omniauth/omniauth/wiki/FAQ#rails-session-is-clobbered-after-callback-on-developer-strategy
  skip_before_action :verify_authenticity_token, only: :facebook

  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication # this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"].except(:extra) # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def index
    @profile = User.search(params[:name])
    @profiles = User.all.to_a.reject! { |e| e[:id] == current_user.id }
  end

  def show
    @profile = User.find(params[:id])
    @posts = @profile.posts  
    @friends = User.searchfriends(params[:id])
  end

end

app/views/users/_navbar.html.erb
  <nav class="bg-[#dadde1] flex flex-col gap-1">
  <div class="bg-[#3b5998] flex py-2.5 relative h-[54px] items-center">
    <%= link_to posts_path do %>
      <span class="material-symbols-outlined text-white pl-2 absolute top-[15px]">arrow_back</span>
    <% end %>
    <p class="text-center text-white flex-1 text-m"><%= name %></p>
  </div>
</nav>

app/views/users/_notification.html.erb
<% invitations = Invitation.where(invited_user_id: current_user.id) %>
<% if invitations.exists? %>
  <% invitations.each do |invitation| %>
    <div class="bg-white flex py-2.5 px-2.5">
      <%= image_tag User.find(invitation.requesting_user_id).avatar.url, class: "rounded-full h-[40px] w-[40px] mr-2.5" %>
      <p class="text-xs flex-1 text-start text-ellipsis">Você tem uma nova solicitação de amizade: <strong><%= User.find(invitation.requesting_user_id).name %></strong></p>
      <%= button_to friends_path, params: {friend_id: invitation.requesting_user_id, user_id: current_user.id }, class: "flex gap-[5px] bg-[#1877f2] items-center text-white text-xs rounded-md py-1 px-[5px] " do %>
        <span class="material-symbols-outlined">person_add</span> Aceitar
      <% end %>
    <% end %>
  </div>
<% else %>
<p class="bg-white flex py-5 px-2.5 text-center ">Você não possui novas notificações!</p>
<% end %>

app/views/users/_searchbar.html.erb
  <% all_users = 0 %>
<%# Search bar %>
<div class="flex items-center text-sm pt-2.5">
  <%= form_tag users_path, method: :get, class: "flex-1 px-2.5" do %>
    <p class="relative"><span class="material-symbols-outlined self-center absolute top-1 left-1">search</span><%= text_field_tag(:name, value = nil, class:"flex flex-1 sitems-center bg-[#e9ebee] py-1.5 pl-[35px] rounded-full w-full text-sm", placeholder: 'Pesquisar' )%></p>
    <%= submit_tag ' ' %>
  <% end %>
</div>
<div class="" data-controller="search">
  <%# All profiles %>
  <p class="px-2.5 text-xs cursor-pointer text-end text-sky-700 mb-2" data-action="click->search#showAll">Mostrar todos os usuários</p>
  <div class="hidden" data-search-target="allProfiles">
    <% @profiles.each do |f| %>
      <%= link_to user_path(f.id), class:"flex gap-1.5 text-[17px] content-center items-center px-2.5 py-2.5 border-t-2" do %>
        <%= render partial: 'shared/show_avatar', :locals => { :user => f, :show_name => "true" }%>
      <% end %>
    <% end %>
  </div>
  <%# Profiles results %>
  <% if @profile %>
    <div class="" data-search-target="searchProfiles">
      <% @profile.each do |f| %>
        <%= link_to user_path(f.id), class:"flex gap-1.5 text-[17px] content-center items-center px-2.5 py-1.5" do %>
        <%= render partial: 'shared/show_avatar', :locals => { :user => f, :show_name => "true" }%>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<%= render 'shared/navbar' %>
<%= render 'users/searchbar' %>

app/views/users/show.html.erb
<% resource = current_user%>
<%= render "users/navbar", name: @profile.name %>
<%# Profile infos %>
<div class="flex justify-center content-center relative">
  <div class="profile-pic z-50 mt-[100px]">
    <div class="flex overflow-hidden h-[142px] w-[142px] rounded-[50%] border-4">
      <% if @profile.uploaded_url == nil %>
        <%= image_tag @profile.avatar.url %>
      <% else %>
        <%= image_tag @profile.uploaded_url %>
      <% end %>
    </div>
    <% if @profile == current_user %>
      <%= simple_form_for(resource, url: registration_path(resource), html: { class: "absolute right-[105px] bottom-[20px]", data: { turbo: false}, :multipart => true, method: :put  }) do |f| %>
        <label class="flex material-symbols-outlined cursor-pointer bg-[#e4e6eb] rounded-full p-0.5 text-center">
          photo_camera
          <span style="display:none;">
            <%= f.file_field :avatar, id: "file-input", onchange: 'this.form.submit();' %>
            <%= f.hidden_field :avatar_cache %>
          </span>
        </label>
      <% end %>
    <% end%>
  </div>
  <div class="cover-pic absolute w-full h-full px-2.5 pt-2.5">
    <div class="flex overflow-hidden rounded-t-lg">
      <% if @profile.cover.url %>
        <%= image_tag @profile.cover.url, class: "w-full h-[200px]" %>
      <% end %>
    </div>
    <% if @profile == current_user %>
      <%= simple_form_for(resource, url: registration_path(resource), html: { class: "absolute right-[20px] bottom-[40px]", data: { turbo: false}, :multipart => true, method: :put  }) do |f| %>
        <label class="flex material-symbols-outlined cursor-pointer bg-[#e4e6eb] rounded-md p-0.5">
          photo_camera
          <span style="display:none;">
            <%= f.file_field :cover, id: "file-input", onchange: 'this.form.submit();' %>
            <%= f.hidden_field :cover_cache %>
          </span>
        </label>
      <% end %>
    <% end %>
  </div>
</div>
<%# Profile buttons %>
<div class="text-center py-1.5 text-[24px]"><%= @profile.name %></div>
<% if @profile == current_user %>
  <%= button_to edit_user_registration_path, method: :get, class: "flex flex-1 gap-[10px] bg-[#1877f2] text-white rounded-md py-1.5 px-[50px] my-1.5 mx-2.5 justify-center", form_class: "flex w-full" do %>
    <span class="material-symbols-outlined">edit</span> Editar perfil
  <% end %>
<% end %>
<% if @profile != current_user %>
  <%# Se não existe um invite criado pelo usuário logado ou pelo perfil visitado e ainda não sao amigos %>
  <% if !Invitation.where(invited_user_id: current_user.id, requesting_user_id: @profile.id)
        .or(Invitation.where(invited_user_id: @profile.id, requesting_user_id: current_user.id)).exists? &&
        !Friend.where(friend_id: @profile.id, user_id: current_user.id).or(Friend.where(friend_id: current_user.id, user_id: @profile.id)).exists? %>
  <%= button_to invitations_path, params: {invited_user_id: @profile.id, requesting_user_id: current_user.id }, class: "flex gap-[10px] bg-[#1877f2] text-white rounded-md py-1.5 px-[50px] my-1.5 mx-2.5" do %>
    <span class="material-symbols-outlined">person_add</span> Adicionar
  <% end %>
  <%# Se existe algum invite vindo de @profile.id para o usuário logado e ainda não existe uma amizade criada %>
<% elsif (Invitation.where(invited_user_id: current_user.id, requesting_user_id: @profile.id).exists? && 
           !Friend.where(friend_id: @profile.id, user_id: current_user.id).or(Friend.where(friend_id: current_user.id, user_id: @profile.id)).exists?) %>
<%= button_to friends_path, params: {friend_id: @profile.id, user_id: current_user.id }, class: "flex gap-[10px] bg-[#1877f2] text-white rounded-md py-1.5 px-[50px] my-1.5 mx-2.5" do %>
  <span class="material-symbols-outlined">person_add</span> Aceitar
<% end %>
<%# Se a amizade já esta estabelecida %>
<% elsif Friend.where(friend_id: @profile.id, user_id: current_user.id).or(Friend.where(friend_id: current_user.id, user_id: @profile.id)).exists?%>
  <% friendship = Friend.where(friend_id: @profile.id, user_id: current_user.id).or(Friend.where(friend_id: current_user.id, user_id: @profile.id))[0] %>
  <%= button_to friend_path(friendship.id), method: :delete, class: "flex flex-1 gap-[10px] bg-[#1877f2] text-white rounded-md py-1.5 px-[50px] my-1.5 mx-2.5 justify-center", form_class: "flex w-full" do %>
    <span class="material-symbols-outlined">cancel</span> Desfazer amizade
  <% end %>
  <%# Se ja existe um pedido de solicitacao de amizade nesse perfil feita pelo usuário logado %>
<% else%>
  <% invite = Invitation.where(invited_user_id: @profile.id, requesting_user_id: current_user.id)[0]%>
  <%= button_to invitation_path(id: invite.id), method: :delete,  class: "flex gap-[10px] bg-[#1877f2] text-white rounded-md py-1.5 px-[50px] my-1.5 mx-2.5" do %>
    <span class="material-symbols-outlined">cancel</span> Cancelar pedido
  <% end %>
<%end%>
<% end%>
<%# Friends %>
<div class="border-t-2 mx-2.5 my-4">
  <p class="text-[20px] mt-2">Amigos</p>
  <p class="text-[17px] text-[#606770]"><%= @friends.count %> amigos</p>
  <div class="flex gap-2.5">
    <% @friends.each do |friend| %>
      <% if friend.friend_id == @profile.id %>
        <%= link_to user_path(friend.user_id) do %>
          <div class="">
            <% if User.find(friend.user_id).avatar.url != nil %>
              <%= image_tag User.find(friend.user_id).avatar.url, class: "h-[120px] w-[120px] rounded-lg" %>
            <% else %>
              <%= image_tag User.find(friend.user_id).uploaded_url, class: "h-[120px] w-[120px] rounded-lg" %>
            <% end %>
            <p class="text-[13px] my-1"><%= User.find(friend.user_id).name %></p>
          </div>
        <% end %>
      <% end %>
      <% if friend.user_id == @profile.id %>
        <%= link_to user_path(friend.friend_id) do %>
          <div class="">
            <% if User.find(friend.friend_id).avatar.url != nil %>
              <%= image_tag User.find(friend.friend_id).avatar.url, class: "h-[120px] w-[120px] rounded-lg" %>
            <% else %>
              <%= image_tag User.find(friend.friend_id).uploaded_url, class: "h-[120px] w-[120px] rounded-lg" %>
            <% end %>
            <p class="text-[13px] my-1"><%= User.find(friend.friend_id).name %></p>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>
<%# Posts %>
<div class="bg-[#dadde1] flex flex-col gap-2.5 py-2.5">
  <%= render "shared/post", posts: @posts%>
</div>