config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    registrations: 'registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :posts
  resources :comments
  resources :likes
  resources :users
  resources :invitations, :only => [:index, :new, :create, :destroy]
  resources :friends, :only => [:index, :new, :create, :destroy]
  resources :conversations
  resources :messages
  
  devise_scope :user do
    root to: "devise/sessions#new"
  end
  get 'profiles', to: 'users#show'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/shared/_create_comment.html.erb
<%= simple_form_for(comment, url: comments_path , html: { data: { turbo: false}, method: :post, class: "flex gap-1.5 pl-2.5"  }) do |f| %>
  <%= f.input :body, as: :text, :required => true, label: false, :input_html => { :class => 'text-xs rounded w-full', :rows => 3, :cols => 20 }, :wrapper_html => { :class => 'w-[80%]'}, placeholder: 'Escreva um comentário...' %>
  <%= f.hidden_field :id, :value => nil %>
  <%= f.hidden_field :user_id, :value => current_user.id %>
  <%= f.hidden_field :post_id, :value => post_id %>
  <%= f.submit 'Publicar', class:"text-[9px] text-center px-2.5 cursor-pointer py-2.5 bg-[#4080ff] text-white rounded-md h-[40px] w-[60px]" %>
<% end %>

app/views/shared/_like_post.html.erb
<% if !Like.where(post_id: post.id, user_id: current_user.id).exists? %>
  <%= button_to likes_path, html: { data: { turbo: false}, method: :post}, params: {user_id: current_user.id, post_id: post.id}, class: "flex items-center content-center" do%>
    <p class="text-xs flex items-center content-center gap-1.5"><span class="material-symbols-outlined text-[18px]">thumb_up</span>Curtir</p>
  <% end %>
<%else %>
  <% like = Like.where(post_id: post.id, user_id: current_user.id).first %>
  <%= button_to like_path(like.id), method: :delete, class: "flex items-center content-center" do%>
    <p class="text-xs flex items-center content-center gap-1.5 text-sky-700 font-bold"><span class="material-symbols-outlined text-[18px]">thumb_up</span>Descurtir</p>
  <% end %>
<%end%>

app/views/shared/_navbar.html.erb
  <nav class="bg-[#dadde1] flex flex-col gap-1">
  <div class="bg-[#3b5998] flex py-2.5 relative h-[54px] items-center">
    <%= link_to posts_path do %>
      <span class="material-symbols-outlined text-white pl-2 absolute top-[15px]">arrow_back</span>
    <% end %>
    <p class="text-center text-white flex-1 text-m">Petbook</p>
  </div>
</nav>

app/views/shared/_post.html.erb
  <% posts.each do |post| %>
  <div class="bg-white flex flex-col min-h-[200px]">
    <div class="flex px-2.5 py-1.5">
      <%= link_to user_path(post.user) do %>
      <%= render partial: 'shared/show_avatar', :locals => { :user => post.user, :show_name => "false" }%>
      <% end %>
      <div class="flex flex-col px-2.5">
        <p class="text-sm"><%= post.user.name%></p>
        <p class="text-xs"><%= Post.timestamp(post.id).map {|key, value| "#{value} #{key}" if value > 0 }.join(' ') %></p>
      </div>
    </div>
    <p class="text-xs px-2.5 py-1"><%= post.body %></p>
    <%# Reactions count %>
    <%= render 'shared/reactions_count', post: post%>

    <%# Reactions %>
    <div class="flex gap-[50px] flex-col text-sm self-center py-2 text-sm justify-end w-full px-[20px]">
      <div class="flex border-t-2 gap-[50px] justify-center items-center h-[30px]">
        <%= render 'shared/like_post', post: post %>
        <%= button_to new_comment_path, method: :get, params: {id: post.id}, class: "flex items-center content-center" do %>
          <p class="text-xs flex items-center gap-1.5"><span class="material-symbols-outlined text-[18px]">mode_comment</span>Comentar</p>
        <% end %>
      </div>
    </div>
  </div>
<% end%>

app/views/shared/_reactions_count.html.erb
    <% if post.likes.count > 0 %>
      <div class="flex flex-col flex-1 justify-end">
        <p class="flex px-2.5 items-center text-sm gap-1.5">
          <span class="material-symbols-outlined flex items-center justify-center bg-[#2f9ffc] rounded-full text-[17px] w-[20px] text-center h-[20px] text-white">thumb_up_off</span>
          <%= post.likes.count %>
        </p>
      </div>
    <% else %>
      <p class="flex flex-col flex-1 justify-end"></p>
    <% end %>

app/views/shared/_show_avatar.html.erb
<% if user.uploaded_url == nil %>
  <%= image_tag user.avatar.url, class: "rounded-full h-[40px] w-[40px]" %>
  <% if local_assigns[:show_name] == "true" %>
    <%= user.name%>
  <% end %>
<% else %>
  <%= image_tag user.uploaded_url, class: "rounded-full h-[40px] w-[40px]" %>
  <% if local_assigns[:show_name] == "true" %>
    <%= user.name%>
  <% end %>
<% end %>