config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    registrations: 'registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :posts
  resources :comments
  resources :likes
  resources :users
  resources :invitations, :only => [:index, :new, :create, :destroy]
  resources :friends, :only => [:index, :new, :create, :destroy]
  resources :conversations
  resources :messages
  
  devise_scope :user do
    root to: "devise/sessions#new"
  end
  get 'profiles', to: 'users#show'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :likes

  def self.timestamp(id)
    post_time = Post.find(id).created_at
    diff = Time.now - post_time
    days, diff = diff.divmod(86_400)
    hours, diff = diff.divmod(3600)
    mins, diff = diff.divmod(60)
    { days: days, h: hours, min: mins }
  end

  def self.timelinePosts(user)
    friends = User.searchfriends(user.id)
    posts = []
    friends.each do |friend|
      posts << if user.id != friend.friend_id
                 Post.where(user_id: friend.friend_id)
               else
                 Post.where(user_id: friend.user_id)
               end
    end
    posts.flatten
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  def index
    @posts = Post.timelinePosts(current_user)
    @profile = User.find(current_user.id)
    @invites_received = Invitation.invites_received(current_user)
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_path }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end
  private
  def post_params
    params.require(:post).permit(:body)
  end

end

app/views/posts/index.html.erb
<div class="bg-[#dadde1] flex flex-col gap-2.5" data-controller="notification">
  <nav class="bg-[#dadde1] flex flex-col gap-1">
    <div class="bg-[#3b5998] grid grid-cols-[1fr_1fr_7fr_1fr_1fr] content-center py-2.5 gap-3">
      <%= link_to user_path(current_user.id) do %>
        <span class="material-symbols-outlined text-white pl-2.5 cursor-pointer text-2xl">account_circle</span>
      <% end %>
      <span class="material-symbols-outlined text-white pl-2.5 text-2xl cursor-pointer" data-action="click->notification#hide">dynamic_feed</span>
      <%= link_to(users_path) do %>
        <p class="cursor-pointer border-b text-white text-center flex text-sm items-center justify-center border-solid"><span class="material-symbols-outlined self-center">search</span>Pesquisar</p>
      <% end %>
      <% if @invites_received.count > 0%>
        <div class="relative"><span class="material-symbols-outlined justify-self-center  text-2xl cursor-pointer text-rose-700" data-action="click->notification#show">notifications</span><span class="absolute top-0 text-rose-700 right-[1px] text-xs"><%= @invites_received.count %></span></div>
      <% else %>
        <span class="material-symbols-outlined justify-self-center cursor-pointer text-2xl text-white" data-action="click->notification#show">notifications</span>
      <% end%>
      <%= link_to conversations_path do %>
        <span class="material-symbols-outlined text-white pr-2.5 text-2xl">chat</span>
      <% end %>
    </div>
    <div class="bg-[#ffffff] grid grid-cols-[2fr_11fr_1fr] py-2.5 px-2.5 gap-1.5">
      <%# Avatar %>
      <%= link_to user_path(current_user.id) do %>
        <%= render partial: 'shared/show_avatar', :locals => { :user => current_user, :show_name => "false" }%>
      <% end %>
      <%= link_to new_post_path do %>
        <p class="text-sm  px-2.5 border-solid border-[1px] rounded-full py-1.5">No que você está pensando?</p>
      <% end %>
      <%= link_to new_post_path do %>
        <span class="material-symbols-outlined justify-self-end text-3xl">image</span>
      <% end %>
    </nav>
    <div data-notification-target="posts" class="flex flex-col gap-2.5">
      <%= render "shared/post", posts: @posts%>
    </div>
    <div data-notification-target="notifications" class="hidden">
      <%= render "users/notification" %>
    </div>
  </div>
</div>
<%= button_to  destroy_user_session_path, :method => :delete, :data => { :no_turbolink => true }, class: "w-full px-2.5 py-2" do %>
  <div class="actions flex justify-center bg-blue-700 rounded my-1.5">
    <p class="text-white flex-1 text-sm py-1">Logout</p>
  </div >
<% end %>

app/views/posts/new.html.erb
<div class="border-solid border-b">
  <%= link_to posts_path do %>
  <p class="flex items-center py-2.5 px-2.5"><span class="material-symbols-outlined pr-2">arrow_back</span>Criar publicação</p>
  <% end %>
</div>
<div class="flex py-1.5 border-solid border-b px-2.5">
        <%= render 'shared/show_avatar', user: current_user %>
  <div class="flex flex-col px-2.5">
    <p><%= current_user.name %></p>
    <p class="text-xs">Compartilhar com: OPÇÕES</p>
  </div>
</div>
<div>
  <%= simple_form_for(@post) do |f| %>
    <div class="field flex my-3 mx-1.5 ">
      <%= f.input :body, label: false, :as => :text, placeholder: "No que você está pensando?", :input_html => {:rows => 10, :cols => 20, :class => "rounded grow h-[200px] w-full"}, :wrapper_html => {:class => "w-full"} %>
    </div>
    <div class="actions flex justify-center bg-blue-700 rounded my-3 mx-1.5 ">
      <%= f.button :submit, "Publicar", class: "text-white text-sm rounded-md py-2.5 cursor-pointer grow bg-blue-700" %>
    </div>
  <% end %>
</div>